logging:
  file:
    name: C:/springcloudtraining/temp/spring-boot-elk3.log

server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: CustomerService
  zipkin:
    base-url: http://localhost:9411/

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shop_customerDB

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

