spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: ProductService
        uri: lb://ProductService
        predicates:
        - Path=/products/**
      - id: ShoppingCommandService
        uri: lb://ShoppingCommandService
        predicates:
        - Path=/CartCommands/**
      - id: ShoppingQueryService
        uri: lb://ShoppingQueryService
        predicates:
        - Path=/CartQueries/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


